#开发环境配置
server:
  port: 8080
  servlet:
    #应用访问路径
    context-path: /

#数据库配置，spring默认的数据库连接池Hikari
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scaffold?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456

